package uk.ac.isc.seiseventselection;

import java.awt.BorderLayout;
import java.awt.Font;
import javax.swing.UIManager;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.util.NbBundle.Messages;
import org.openide.windows.TopComponent;
import uk.ac.isc.seisdata.VBASLogger;


/**
 * Top component which displays the events control list that the analyst can
 * select for the review. multi-selection is disabled as the current review is
 * based on single selection use this class to load data and make changes and
 * the view cannot be closed
 */
@ConvertAsProperties(
        dtd = "-//uk.ac.isc.seiseventselection//EventsControlView//EN",
        autostore = false
)
@TopComponent.Description(
        preferredID = "SeisEventSelectionTopComponent",
        //iconBase="SET/PATH/TO/ICON/HERE", 
        persistenceType = TopComponent.PERSISTENCE_ALWAYS
)
@TopComponent.Registration(mode = "explorer", openAtStartup = true)
@ActionID(category = "Window", id = "uk.ac.isc.seiseventselection.SeisEventSelectionTopComponent")
@ActionReference(path = "Menu/Window" /*, position = 333 */)
@TopComponent.OpenActionRegistration(
        displayName = "#CTL_SeisEventSelectionViewAction",
        preferredID = "SeisEventSelection Window"
)
@Messages({
    "CTL_SeisEventSelectionViewAction=SeisEvent Selection",
    "CTL_SeisEventSelectionTopComponent=SeisEvent Selection",
    "HINT_SeisEventSelectionTopComponent=SeisEvent Selection"
})

public final class SeisEventSelectionTopComponent extends TopComponent {

    SeisEventsTable eventsTable;                    // Event Table

    public SeisEventSelectionTopComponent() {
        initComponents();
        setName(Bundle.CTL_SeisEventSelectionTopComponent());
        setToolTipText(Bundle.HINT_SeisEventSelectionTopComponent());
        putClientProperty(TopComponent.PROP_CLOSING_DISABLED, Boolean.TRUE);
        putClientProperty(TopComponent.PROP_SLIDING_DISABLED, Boolean.FALSE);
        putClientProperty(TopComponent.PROP_UNDOCKING_DISABLED, Boolean.FALSE);
        //setName("SeisEvent Selection");

        VBASLogger.logDebug("Here...");

        eventsTable = new SeisEventsTable();
        this.setLayout(new BorderLayout());
        this.add(eventsTable, BorderLayout.CENTER);
        
        //setLocation();
    }

    /* 
     * return of the control panel, all the data is in this class.
     */
    public SeisEventsTable getControlPanel() {
        return this.eventsTable;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {
        // TODO add custom code on component opening
        UIManager.put("ToolTip.font", new Font("Arial", Font.BOLD, 18));

    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }

}
