/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mytable;

import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author saiful
 */
public class PhaseEditDialog extends javax.swing.JFrame {

    /**
     * Creates new form RelocateFrame
     */
    public PhaseEditDialog() {
        initComponents();
               
    }

 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        buttonOK = new javax.swing.JButton();
        buttonCancel = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_edit = new javax.swing.JTable();
        textField_timeShift = new javax.swing.JTextField();
        textField_put = new javax.swing.JTextField();
        button_applyToAll = new javax.swing.JButton();
        comboBox_fix = new javax.swing.JComboBox();
        comboBox_nondef = new javax.swing.JComboBox();
        comboBox_deleteAmp = new javax.swing.JComboBox();
        comboBox_phaseBreak = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Edit Phase");

        buttonOK.setBackground(new java.awt.Color(45, 137, 239));
        buttonOK.setForeground(new java.awt.Color(255, 255, 255));
        buttonOK.setText("OK");
        buttonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOKActionPerformed(evt);
            }
        });

        buttonCancel.setBackground(new java.awt.Color(45, 137, 239));
        buttonCancel.setForeground(new java.awt.Color(255, 255, 255));
        buttonCancel.setText("Cancel");
        buttonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Input"));

        table_edit.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Phase ID", "Type", "Fix", "Nondef", "Time Shift +/- n (mdh)", "Delete Amp", "Phase Break", "Put (Value)"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.String.class, java.lang.Boolean.class, java.lang.Object.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, true, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table_edit);

        textField_timeShift.setText("NA");
        textField_timeShift.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField_timeShiftActionPerformed(evt);
            }
        });

        textField_put.setText("NA");
        textField_put.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField_putActionPerformed(evt);
            }
        });

        button_applyToAll.setBackground(new java.awt.Color(45, 137, 239));
        button_applyToAll.setForeground(new java.awt.Color(255, 255, 255));
        button_applyToAll.setText("Apply to all");
        button_applyToAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_applyToAllActionPerformed(evt);
            }
        });

        comboBox_fix.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "NA", "Set", "Unset" }));
        comboBox_fix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBox_fixActionPerformed(evt);
            }
        });

        comboBox_nondef.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "NA", "Set", "Unset" }));
        comboBox_nondef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBox_nondefActionPerformed(evt);
            }
        });

        comboBox_deleteAmp.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "NA", "Set", "Unset" }));
        comboBox_deleteAmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBox_deleteAmpActionPerformed(evt);
            }
        });

        comboBox_phaseBreak.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "NA", "Take", "Delete", "Put" }));
        comboBox_phaseBreak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBox_phaseBreakActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(button_applyToAll)
                .addGap(78, 78, 78)
                .addComponent(comboBox_fix, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboBox_nondef, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textField_timeShift, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboBox_deleteAmp, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboBox_phaseBreak, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textField_put, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_applyToAll)
                    .addComponent(comboBox_fix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBox_nondef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textField_timeShift, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBox_deleteAmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBox_phaseBreak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textField_put, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(buttonOK, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(buttonCancel))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonOK)
                    .addComponent(buttonCancel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
   
    

    private void buttonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOKActionPerformed
          
    }//GEN-LAST:event_buttonOKActionPerformed

    private void buttonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_buttonCancelActionPerformed

    private void textField_timeShiftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField_timeShiftActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField_timeShiftActionPerformed

    private void textField_putActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField_putActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField_putActionPerformed

    private void button_applyToAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_applyToAllActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button_applyToAllActionPerformed

    private void comboBox_fixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBox_fixActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBox_fixActionPerformed

    private void comboBox_nondefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBox_nondefActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBox_nondefActionPerformed

    private void comboBox_deleteAmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBox_deleteAmpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBox_deleteAmpActionPerformed

    private void comboBox_phaseBreakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBox_phaseBreakActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBox_phaseBreakActionPerformed

    
    
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCancel;
    private javax.swing.JButton buttonOK;
    private javax.swing.JButton button_applyToAll;
    private javax.swing.JComboBox comboBox_deleteAmp;
    private javax.swing.JComboBox comboBox_fix;
    private javax.swing.JComboBox comboBox_nondef;
    private javax.swing.JComboBox comboBox_phaseBreak;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_edit;
    private javax.swing.JTextField textField_put;
    private javax.swing.JTextField textField_timeShift;
    // End of variables declaration//GEN-END:variables
}
