package uk.ac.isc.phaseview;

import java.awt.BorderLayout;
import javax.swing.JScrollPane;
import javax.swing.JSplitPane;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.util.NbBundle.Messages;
import org.openide.windows.TopComponent;
import uk.ac.isc.seisdatainterface.Global;
import uk.ac.isc.seisdata.Hypocentre;
import uk.ac.isc.seisdata.HypocentresList;
import uk.ac.isc.seisdata.PhasesList;
import uk.ac.isc.seisdata.SeisDataChangeEvent;
import uk.ac.isc.seisdata.SeisDataChangeListener;
import uk.ac.isc.seisdata.SeisEvent;
import uk.ac.isc.seisdata.VBASLogger;

/**
 * Top component which displays the phase view.
 */
@ConvertAsProperties(
        dtd = "-//uk.ac.isc.phaseview//PhaseView//EN",
        autostore = false
)
@TopComponent.Description(
        preferredID = "PhaseViewTopComponent",
        //iconBase="SET/PATH/TO/ICON/HERE",
        persistenceType = TopComponent.PERSISTENCE_ALWAYS
)
@TopComponent.Registration(mode = "explorer", openAtStartup = true)
@ActionID(category = "Window", id = "uk.ac.isc.phaseview.PhaseViewTopComponent")
@ActionReference(path = "Menu/Window" /*, position = 333 */)
@TopComponent.OpenActionRegistration(
        displayName = "#CTL_PhaseViewAction",
        preferredID = "PhaseViewTopComponent"
)
@Messages({
    "CTL_PhaseViewAction=PhaseView",
    "CTL_PhaseViewTopComponent=PhaseView Window",
    "HINT_PhaseViewTopComponent=This is a PhaseView window"
})
public final class PhaseViewTopComponent extends TopComponent implements SeisDataChangeListener {

    private JSplitPane pairViewsPane = null;
    private PhaseViewControlPanel phaseViewControlPanel = null;
    private JScrollPane leftPane = null;
    private JScrollPane rightPane = null;
    private PhaseTravelViewPanel phaseTVPanel = null;
    private PhaseDetailViewPanel phaseDVPanel = null;

    private boolean showTTDFlag = true;
    // Other
    private Hypocentre primeHypocentre;
    // Data
    private static final SeisEvent selectedSeisEvent = Global.getSelectedSeisEvent();
    private final HypocentresList hypocentresList = Global.getHypocentresList();
    private static final PhasesList phasesList = Global.getPhasesList();
    // selected phase in Phase Selection table
    private static final PhasesList selectedPhaseList = Global.getSelectedPhaseList();

    // Pane and panels for views
    public PhaseViewTopComponent() {
        initComponents();
        setName(Bundle.CTL_PhaseViewTopComponent());
        setToolTipText(Bundle.HINT_PhaseViewTopComponent());
        putClientProperty(TopComponent.PROP_CLOSING_DISABLED, Boolean.TRUE);
        putClientProperty(TopComponent.PROP_SLIDING_DISABLED, Boolean.TRUE);
        putClientProperty(TopComponent.PROP_UNDOCKING_DISABLED, Boolean.TRUE);
        setName("Phase TT Curves");

        VBASLogger.logDebug("Loaded...");

        selectedSeisEvent.addChangeListener(this);
        selectedPhaseList.addChangeListener(this);
        
        /* 
         * Create 2 phase views. 
         */
        phaseTVPanel = new PhaseTravelViewPanel(phasesList, hypocentresList);
        phaseDVPanel = new PhaseDetailViewPanel(phaseTVPanel);

        phaseViewControlPanel = new PhaseViewControlPanel(phaseTVPanel, phaseDVPanel);
        // add them together to the top component
        leftPane = new JScrollPane(phaseTVPanel);
        rightPane = new JScrollPane(phaseDVPanel);
        pairViewsPane = new JSplitPane(JSplitPane.HORIZONTAL_SPLIT, leftPane, rightPane);
        pairViewsPane.setResizeWeight(0.5d);
        this.setLayout(new BorderLayout());
        this.add(phaseViewControlPanel, BorderLayout.NORTH);
        this.add(pairViewsPane, BorderLayout.CENTER);

    }

    @Override
    public void SeisDataChanged(SeisDataChangeEvent event) {
        String eventName = event.getData().getClass().getName();
        //VBASLogger.logDebug("Event received from: " + eventName);
        switch (eventName) {
            case "uk.ac.isc.seisdata.SeisEvent":
                //SeisEvent seisEvent = (SeisEvent) event.getData();
                VBASLogger.logDebug("SeisEvent= " + selectedSeisEvent.getEvid());

                phaseViewControlPanel.reset();
                phaseTVPanel.updateData();
                phaseDVPanel.updateData();
                break;

            case "uk.ac.isc.seisdata.PhasesList":
                VBASLogger.logDebug("In case:" + eventName);

                // TODO: do not redraw everything!
                //Hypocentre hypocentre = (Hypocentre) event.getData();
                //VBASLogger.logDebug("Hypocentre= " + selectedHypocentre.getHypid());
                
                break;
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {
        // TODO add custom code on component opening
        //phasesList.addChangeListener(this);
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
        //phasesList.removeChangeListener(this);
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }

}
