/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uk.ac.isc.processcommand;

import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import uk.ac.isc.seisdata.Command;
import uk.ac.isc.seisdata.SeisEvent;
import uk.ac.isc.seisdata.VBASLogger;
import uk.ac.isc.seisdatainterface.FormulateCommand;
import uk.ac.isc.seisdatainterface.Global;
import uk.ac.isc.seisdatainterface.SeisDataDAO;

/**
 *
 * @author saiful
 */
public class ManualCommand extends javax.swing.JDialog {

    private final Command commandEvent = Global.getCommandEvent();

    public ManualCommand() {
        setModal(true);
        initComponents();
        groupRadioButton();
    }

    private void groupRadioButton() {
        ButtonGroup group = new ButtonGroup();
        //group.add(this.radioButton_create);
        group.add(this.radioButton_merge);
    }

    public void showManualCommandDialog(int seisEvent) {
        text_mergeDest.setText(String.valueOf(seisEvent));
        this.setVisible(true);
    }

    private void oKActionPerformed() {

        FormulateCommand formulateCommand = null;
        String commandType = "";

        if (radioButton_merge.isSelected()) {
            Integer src = null;
            Integer dest = null;
            try {
                src = Integer.parseInt(text_mergeSrc.getText());
                dest = Integer.parseInt(text_mergeDest.getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Merge : incorrect input value.", "Error",
                        JOptionPane.ERROR_MESSAGE);
                return;
            }

            commandType = "merge";
            formulateCommand = new FormulateCommand(commandType, "seisevent", dest, "");
            formulateCommand.addAttribute("siesevent", dest, src);
            formulateCommand.addSQLFunction("merge (" + src + ", " + dest + " )");

        } /*else if (radioButton_create.isSelected()) {
            JOptionPane.showMessageDialog(null, "Create: will be enabled in the next release.",
                    "Warning",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }*/

        if (formulateCommand != null) {
            if (formulateCommand.isValidSystemCommand()) {

                VBASLogger.logDebug("\ncommandLog= " + formulateCommand.getCmdProvenance().toString()
                        + "\nsystemCommand= " + formulateCommand.getSystemCommand().toString());

                boolean ret = SeisDataDAO.updateCommandTable(Global.getSelectedSeisEvent().getEvid(), commandType,
                        formulateCommand.getCmdProvenance().toString(), formulateCommand.getSystemCommand().toString());

                if (ret) {
                    VBASLogger.logDebug(" Fired: " + commandType);
                    commandEvent.fireSeisDataChanged();
                } else {
                    JOptionPane.showMessageDialog(null, "Incorrect Command.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        }

        this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_merge = new javax.swing.JPanel();
        radioButton_merge = new javax.swing.JRadioButton();
        text_mergeDest = new javax.swing.JTextField();
        text_mergeSrc = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        button_Cancel = new javax.swing.JButton();
        button_OK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panel_merge.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        org.openide.awt.Mnemonics.setLocalizedText(radioButton_merge, org.openide.util.NbBundle.getMessage(ManualCommand.class, "ManualCommand.radioButton_merge.text")); // NOI18N

        text_mergeDest.setText(org.openide.util.NbBundle.getMessage(ManualCommand.class, "ManualCommand.text_mergeDest.text")); // NOI18N
        text_mergeDest.setToolTipText(org.openide.util.NbBundle.getMessage(ManualCommand.class, "ManualCommand.text_mergeDest.toolTipText")); // NOI18N

        text_mergeSrc.setText(org.openide.util.NbBundle.getMessage(ManualCommand.class, "ManualCommand.text_mergeSrc.text")); // NOI18N
        text_mergeSrc.setToolTipText(org.openide.util.NbBundle.getMessage(ManualCommand.class, "ManualCommand.text_mergeSrc.toolTipText")); // NOI18N
        text_mergeSrc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_mergeSrcActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(ManualCommand.class, "ManualCommand.jLabel1.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(ManualCommand.class, "ManualCommand.jLabel2.text")); // NOI18N

        javax.swing.GroupLayout panel_mergeLayout = new javax.swing.GroupLayout(panel_merge);
        panel_merge.setLayout(panel_mergeLayout);
        panel_mergeLayout.setHorizontalGroup(
            panel_mergeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_mergeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(radioButton_merge)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_mergeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(text_mergeSrc, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(panel_mergeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel2)
                    .addComponent(text_mergeDest, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );
        panel_mergeLayout.setVerticalGroup(
            panel_mergeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_mergeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_mergeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_mergeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_mergeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(radioButton_merge)
                        .addComponent(text_mergeSrc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(text_mergeDest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        org.openide.awt.Mnemonics.setLocalizedText(button_Cancel, org.openide.util.NbBundle.getMessage(ManualCommand.class, "ManualCommand.button_Cancel.text")); // NOI18N
        button_Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_CancelActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(button_OK, org.openide.util.NbBundle.getMessage(ManualCommand.class, "ManualCommand.button_OK.text")); // NOI18N
        button_OK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_OKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(243, Short.MAX_VALUE)
                .addComponent(button_Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button_OK, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_Cancel)
                    .addComponent(button_OK)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(panel_merge, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panel_merge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void text_mergeSrcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_mergeSrcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_mergeSrcActionPerformed

    private void button_OKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_OKActionPerformed
        oKActionPerformed();
    }//GEN-LAST:event_button_OKActionPerformed

    private void button_CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_CancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_button_CancelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_Cancel;
    private javax.swing.JButton button_OK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel panel_merge;
    private javax.swing.JRadioButton radioButton_merge;
    private javax.swing.JTextField text_mergeDest;
    private javax.swing.JTextField text_mergeSrc;
    // End of variables declaration//GEN-END:variables

}
