package uk.ac.isc.stationmagnitudeview;

import java.awt.BorderLayout;
import javax.swing.JScrollPane;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.util.NbBundle.Messages;
import org.openide.windows.TopComponent;
import org.openide.windows.WindowManager;
import uk.ac.isc.eventscontrolview.EventsControlViewTopComponent;
import uk.ac.isc.seisdata.Hypocentre;
import uk.ac.isc.seisdata.HypocentresList;
import uk.ac.isc.seisdata.SeisDataChangeEvent;
import uk.ac.isc.seisdata.SeisDataChangeListener;

/**
 * Top component which displays the station magnitude view.
 */
@ConvertAsProperties(
        dtd = "-//uk.ac.isc.stationmagnitudeview//StationMagnitudeView//EN",
        autostore = false
)
@TopComponent.Description(
        preferredID = "StationMagnitudeViewTopComponent",
        //iconBase="SET/PATH/TO/ICON/HERE", 
        persistenceType = TopComponent.PERSISTENCE_ALWAYS
)
@TopComponent.Registration(mode = "magnitudeview", openAtStartup = false)
@ActionID(category = "Window", id = "uk.ac.isc.stationmagnitudeview.StationMagnitudeViewTopComponent")
@ActionReference(path = "Menu/Window" /*, position = 333 */)
@TopComponent.OpenActionRegistration(
        displayName = "#CTL_StationMagnitudeViewAction",
        preferredID = "StationMagnitudeViewTopComponent"
)
@Messages({
    "CTL_StationMagnitudeViewAction=StationMagnitudeView",
    "CTL_StationMagnitudeViewTopComponent=StationMagnitudeView Window",
    "HINT_StationMagnitudeViewTopComponent=This is a StationMagnitudeView window"
})
public final class StationMagnitudeViewTopComponent extends TopComponent implements SeisDataChangeListener {

    //hypo list data
    private final HypocentresList hyposList;

    //get control window to retrieve data
    private final TopComponent tc = WindowManager.getDefault().findTopComponent("EventsControlViewTopComponent");

    private JScrollPane scrollPane = null;

    //prime hypo
    private Hypocentre ph;

    //the key object of the view    
    private StationMagnitudeView smView;

    public StationMagnitudeViewTopComponent() {
        initComponents();
        setName(Bundle.CTL_StationMagnitudeViewTopComponent());
        setToolTipText(Bundle.HINT_StationMagnitudeViewTopComponent());

        hyposList = ((EventsControlViewTopComponent) tc).getControlPanel().getHyposList();

        for (int i = 0; i < hyposList.getHypocentres().size(); i++) {
            if (hyposList.getHypocentres().get(i).getIsPrime()) {
                ph = hyposList.getHypocentres().get(i);
            }
        }

        smView = new StationMagnitudeView(ph);

        scrollPane = new JScrollPane(smView);

        //if(!"ISC".equals(ph.getAgency()) || ph.getAgency()==null)
        //{
        //   return;
        //}
        this.setLayout(new BorderLayout());
        this.add(scrollPane, BorderLayout.CENTER);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {
        // TODO add custom code on component opening
        hyposList.addChangeListener(this);
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
        hyposList.removeChangeListener(this);
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }

    //when the hypolist fire a data change event, this function will be called to update the view
    @Override
    public void SeisDataChanged(SeisDataChangeEvent event) {

        for (int i = 0; i < hyposList.getHypocentres().size(); i++) {
            if (hyposList.getHypocentres().get(i).getIsPrime()) {
                ph = hyposList.getHypocentres().get(i);
            }
        }

        //if(!"ISC".equals(ph.getAgency()) || ph.getAgency()==null)
        //{
        //    return;
        //}
        //scrollPane.removeAll();
        smView.reset(ph);
        //scrollPane.add(smView);
        scrollPane.setViewportView(smView);
    }
}
