/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uk.ac.isc.hypooverview;

import java.awt.BorderLayout;
import javax.swing.JScrollPane;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.util.NbBundle.Messages;
import org.openide.windows.TopComponent;
import uk.ac.isc.seisdatainterface.Global;
import uk.ac.isc.seisdata.Hypocentre;
import uk.ac.isc.seisdata.HypocentresList;
import uk.ac.isc.seisdata.SeisDataChangeEvent;
import uk.ac.isc.seisdata.SeisDataChangeListener;
import uk.ac.isc.seisdata.SeisEvent;
import uk.ac.isc.seisdata.VBASLogger;

/**
 * Top component which displays seismicity map and hypocentre position.
 */
@ConvertAsProperties(
        dtd = "-//uk.ac.isc.hypooverview//HypoOverview//EN",
        autostore = false
)
@TopComponent.Description(
        preferredID = "HypoOverviewTopComponent",
        //iconBase="SET/PATH/TO/ICON/HERE", 
        persistenceType = TopComponent.PERSISTENCE_ALWAYS
)
@TopComponent.Registration(mode = "explorer", openAtStartup = true)
@ActionID(category = "Window", id = "uk.ac.isc.hypooverview.HypoOverviewTopComponent")
@ActionReference(path = "Menu/Window" /*, position = 333 */)
@TopComponent.OpenActionRegistration(
        displayName = "#CTL_HypoOverviewAction",
        preferredID = "HypoOverviewTopComponent"
)
@Messages({
    "CTL_HypoOverviewAction=Hypocentre Seismicity",
    "CTL_HypoOverviewTopComponent=Hypocentre Seismicity",
    "HINT_HypoOverviewTopComponent=Hypocentre Seismicity"
})
public final class HypoOverviewTopComponent extends TopComponent implements SeisDataChangeListener {

    private final HypocentresList hypoList = Global.getHypocentresList();
    private static final SeisEvent selectedSeisEvent = Global.getSelectedSeisEvent();       // to receive events
    private static final Hypocentre selectedHypocentre = Global.getSelectedHypocentre();    // to receive events

    private final JScrollPane scrollPane;
    private final HypoOverviewPanel2 overviewPanel;           // the main view
    private final OverviewControlPanel3 controlPanel;        // the control panel

    public HypoOverviewTopComponent() {
        initComponents();
        setName(Bundle.CTL_HypoOverviewTopComponent());
        setToolTipText(Bundle.HINT_HypoOverviewTopComponent());
        putClientProperty(TopComponent.PROP_CLOSING_DISABLED, Boolean.TRUE);
        putClientProperty(TopComponent.PROP_SLIDING_DISABLED, Boolean.FALSE);
        putClientProperty(TopComponent.PROP_UNDOCKING_DISABLED, Boolean.FALSE);
        //setName("Hypocentre Seismicity");

        VBASLogger.logDebug("Loaded...");

        selectedSeisEvent.addChangeListener(this);
        selectedHypocentre.addChangeListener(this);

        overviewPanel = new HypoOverviewPanel2(hypoList);
        controlPanel = new OverviewControlPanel3(overviewPanel);
        
        scrollPane = new JScrollPane(overviewPanel);
        this.setLayout(new BorderLayout());
        this.add(controlPanel, BorderLayout.WEST);
        this.add(scrollPane, BorderLayout.CENTER);
    }

    // repaint when the data changes
    @Override
    public void SeisDataChanged(SeisDataChangeEvent event) {
        String eventName = event.getData().getClass().getName();
        VBASLogger.logDebug("Event received from: " + eventName);

        switch (eventName) {
            case "uk.ac.isc.seisdata.SeisEvent":
                //SeisEvent seisEvent = (SeisEvent) event.getData();
                VBASLogger.logDebug("SeisEvent= " + selectedSeisEvent.getEvid());

                for (Hypocentre hypo : hypoList.getHypocentres()) {
                    if (hypo.getIsPrime() == true) {
                        overviewPanel.setCentLatLon(hypo.getLat(), hypo.getLon());
                        overviewPanel.setCentDepth(hypo.getDepth());
                        overviewPanel.loadSeisData(hypo.getLat(), hypo.getLon(), overviewPanel.getRangeDelta());
                    }
                }

                overviewPanel.repaint();
                scrollPane.setViewportView(overviewPanel);

                controlPanel.resetToDefault();
                controlPanel.repaint();

                break;

            case "uk.ac.isc.seisdata.Hypocentre":
                //Hypocentre hypocentre = (Hypocentre) event.getData();
                VBASLogger.logDebug("Hypocentre= " + selectedHypocentre.getHypid());
                overviewPanel.repaint();
                scrollPane.setViewportView(overviewPanel);

                break;
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {
        // TODO add custom code on component opening
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
        // hypoList.removeChangeListener(this);
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }

}
