package uk.ac.isc.hypooverview;

import javax.swing.ImageIcon;
import javax.swing.JCheckBox;
import javax.swing.JSlider;
import uk.ac.isc.seisdata.VBASLogger;

/**
 *
 * Control panel for controlling the things shown on the main map
 *
 *  
 */
public class OverviewControlPanel3 extends javax.swing.JPanel {

    private final HypoOverviewPanel2 hop;
    private final JCheckBox[] checkBoxRef = new JCheckBox[8];

    /**
     * Creates new form OverviewControlPanel3
     */
    public OverviewControlPanel3(final HypoOverviewPanel2 hop) {
        initComponents();

        this.hop = hop;

        //get the refs point to the static boxes
        checkBoxRef[0] = jCheckBox1;
        checkBoxRef[1] = jCheckBox2;
        checkBoxRef[2] = jCheckBox3;
        checkBoxRef[3] = jCheckBox4;
        checkBoxRef[4] = jCheckBox5;
        checkBoxRef[5] = jCheckBox6;
        checkBoxRef[6] = jCheckBox7;
        checkBoxRef[7] = jCheckBox8;

        resetToDefault();
    }

    public void resetToDefault() {
        VBASLogger.logDebug("...");

        radioButton1_CB.setSelected(true);
        radioButton_Static.setSelected(true);
        setAllBandsSelected();
        hop.setDepthBandOrder(4);

        //slider_bandSelection.setValue(7 - hop.getCurrentBand()); // comment - solves the Issue #35
        // Mini-map on the control panel.
        /*
         ImageIcon map = new ImageIcon(hop.getMiniMap());
         jLabel_miniMap.setIcon(map);
         jLabel_miniMap.revalidate();
         jLabel_miniMap.repaint();
         */
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        radioButton2_DB = new javax.swing.JRadioButton();
        radioButton3_SB = new javax.swing.JRadioButton();
        radioButton5_An = new javax.swing.JRadioButton();
        radioButton4_RO = new javax.swing.JRadioButton();
        radioButton1_CB = new javax.swing.JRadioButton();
        radioButton6_SS = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        slider_bandSelection = new javax.swing.JSlider();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        radioButton_Static = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton9 = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        radioButton_Middle = new javax.swing.JRadioButton();
        jRadioButton12 = new javax.swing.JRadioButton();
        jRadioButton10 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();

        buttonGroup1.add(radioButton2_DB);
        org.openide.awt.Mnemonics.setLocalizedText(radioButton2_DB, org.openide.util.NbBundle.getMessage(OverviewControlPanel3.class, "OverviewControlPanel3.radioButton2_DB.text")); // NOI18N
        radioButton2_DB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButton2_DBActionPerformed(evt);
            }
        });

        buttonGroup1.add(radioButton3_SB);
        org.openide.awt.Mnemonics.setLocalizedText(radioButton3_SB, org.openide.util.NbBundle.getMessage(OverviewControlPanel3.class, "OverviewControlPanel3.radioButton3_SB.text")); // NOI18N
        radioButton3_SB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButton3_SBActionPerformed(evt);
            }
        });

        buttonGroup1.add(radioButton5_An);
        org.openide.awt.Mnemonics.setLocalizedText(radioButton5_An, org.openide.util.NbBundle.getMessage(OverviewControlPanel3.class, "OverviewControlPanel3.radioButton5_An.text")); // NOI18N
        radioButton5_An.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButton5_AnActionPerformed(evt);
            }
        });

        buttonGroup1.add(radioButton4_RO);
        org.openide.awt.Mnemonics.setLocalizedText(radioButton4_RO, org.openide.util.NbBundle.getMessage(OverviewControlPanel3.class, "OverviewControlPanel3.radioButton4_RO.text")); // NOI18N
        radioButton4_RO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButton4_ROActionPerformed(evt);
            }
        });

        buttonGroup1.add(radioButton1_CB);
        radioButton1_CB.setSelected(true);
        org.openide.awt.Mnemonics.setLocalizedText(radioButton1_CB, org.openide.util.NbBundle.getMessage(OverviewControlPanel3.class, "OverviewControlPanel3.radioButton1_CB.text")); // NOI18N
        radioButton1_CB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButton1_CBActionPerformed(evt);
            }
        });

        buttonGroup1.add(radioButton6_SS);
        org.openide.awt.Mnemonics.setLocalizedText(radioButton6_SS, org.openide.util.NbBundle.getMessage(OverviewControlPanel3.class, "OverviewControlPanel3.radioButton6_SS.text")); // NOI18N
        radioButton6_SS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButton6_SSActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(OverviewControlPanel3.class, "OverviewControlPanel3.jLabel1.text")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radioButton2_DB)
                    .addComponent(radioButton1_CB)
                    .addComponent(radioButton3_SB)
                    .addComponent(radioButton4_RO)
                    .addComponent(radioButton5_An)
                    .addComponent(radioButton6_SS)
                    .addComponent(jLabel1))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioButton1_CB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioButton2_DB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioButton3_SB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioButton4_RO)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioButton5_An)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioButton6_SS)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jCheckBox3.setSelected(true);
        org.openide.awt.Mnemonics.setLocalizedText(jCheckBox3, org.openide.util.NbBundle.getMessage(OverviewControlPanel3.class, "OverviewControlPanel3.jCheckBox3.text")); // NOI18N
        jCheckBox3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });

        jCheckBox6.setSelected(true);
        org.openide.awt.Mnemonics.setLocalizedText(jCheckBox6, org.openide.util.NbBundle.getMessage(OverviewControlPanel3.class, "OverviewControlPanel3.jCheckBox6.text")); // NOI18N
        jCheckBox6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jCheckBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox6ActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(OverviewControlPanel3.class, "OverviewControlPanel3.jLabel2.text")); // NOI18N

        slider_bandSelection.setMaximum(7);
        slider_bandSelection.setOrientation(javax.swing.JSlider.VERTICAL);
        slider_bandSelection.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        slider_bandSelection.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slider_bandSelectionStateChanged(evt);
            }
        });

        jCheckBox1.setSelected(true);
        org.openide.awt.Mnemonics.setLocalizedText(jCheckBox1, org.openide.util.NbBundle.getMessage(OverviewControlPanel3.class, "OverviewControlPanel3.jCheckBox1.text")); // NOI18N
        jCheckBox1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jCheckBox5.setSelected(true);
        org.openide.awt.Mnemonics.setLocalizedText(jCheckBox5, org.openide.util.NbBundle.getMessage(OverviewControlPanel3.class, "OverviewControlPanel3.jCheckBox5.text")); // NOI18N
        jCheckBox5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jCheckBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox5ActionPerformed(evt);
            }
        });

        jCheckBox4.setSelected(true);
        org.openide.awt.Mnemonics.setLocalizedText(jCheckBox4, org.openide.util.NbBundle.getMessage(OverviewControlPanel3.class, "OverviewControlPanel3.jCheckBox4.text")); // NOI18N
        jCheckBox4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jCheckBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox4ActionPerformed(evt);
            }
        });

        jCheckBox8.setSelected(true);
        org.openide.awt.Mnemonics.setLocalizedText(jCheckBox8, org.openide.util.NbBundle.getMessage(OverviewControlPanel3.class, "OverviewControlPanel3.jCheckBox8.text")); // NOI18N
        jCheckBox8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jCheckBox8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox8ActionPerformed(evt);
            }
        });

        jCheckBox2.setSelected(true);
        org.openide.awt.Mnemonics.setLocalizedText(jCheckBox2, org.openide.util.NbBundle.getMessage(OverviewControlPanel3.class, "OverviewControlPanel3.jCheckBox2.text")); // NOI18N
        jCheckBox2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });

        jCheckBox7.setSelected(true);
        org.openide.awt.Mnemonics.setLocalizedText(jCheckBox7, org.openide.util.NbBundle.getMessage(OverviewControlPanel3.class, "OverviewControlPanel3.jCheckBox7.text")); // NOI18N
        jCheckBox7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jCheckBox7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(slider_bandSelection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox1)
                            .addComponent(jCheckBox2)
                            .addComponent(jCheckBox3)
                            .addComponent(jCheckBox4)
                            .addComponent(jCheckBox5)
                            .addComponent(jCheckBox6)
                            .addComponent(jCheckBox7)
                            .addComponent(jCheckBox8)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(16, 16, 16)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jCheckBox1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox8))
                    .addComponent(slider_bandSelection, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
        );

        org.openide.awt.Mnemonics.setLocalizedText(jLabel3, org.openide.util.NbBundle.getMessage(OverviewControlPanel3.class, "OverviewControlPanel3.jLabel3.text")); // NOI18N

        buttonGroup2.add(radioButton_Static);
        radioButton_Static.setSelected(true);
        org.openide.awt.Mnemonics.setLocalizedText(radioButton_Static, org.openide.util.NbBundle.getMessage(OverviewControlPanel3.class, "OverviewControlPanel3.radioButton_Static.text")); // NOI18N
        radioButton_Static.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButton_StaticActionPerformed(evt);
            }
        });

        buttonGroup2.add(jRadioButton7);
        org.openide.awt.Mnemonics.setLocalizedText(jRadioButton7, org.openide.util.NbBundle.getMessage(OverviewControlPanel3.class, "OverviewControlPanel3.jRadioButton7.text")); // NOI18N
        jRadioButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton7ActionPerformed(evt);
            }
        });

        buttonGroup2.add(jRadioButton9);
        org.openide.awt.Mnemonics.setLocalizedText(jRadioButton9, org.openide.util.NbBundle.getMessage(OverviewControlPanel3.class, "OverviewControlPanel3.jRadioButton9.text")); // NOI18N
        jRadioButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jRadioButton7)
                    .addComponent(radioButton_Static)
                    .addComponent(jRadioButton9))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioButton_Static)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton9)
                .addContainerGap())
        );

        buttonGroup3.add(radioButton_Middle);
        radioButton_Middle.setSelected(true);
        org.openide.awt.Mnemonics.setLocalizedText(radioButton_Middle, org.openide.util.NbBundle.getMessage(OverviewControlPanel3.class, "OverviewControlPanel3.radioButton_Middle.text")); // NOI18N
        radioButton_Middle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButton_MiddleActionPerformed(evt);
            }
        });

        buttonGroup3.add(jRadioButton12);
        org.openide.awt.Mnemonics.setLocalizedText(jRadioButton12, org.openide.util.NbBundle.getMessage(OverviewControlPanel3.class, "OverviewControlPanel3.jRadioButton12.text")); // NOI18N
        jRadioButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton12ActionPerformed(evt);
            }
        });

        buttonGroup3.add(jRadioButton10);
        org.openide.awt.Mnemonics.setLocalizedText(jRadioButton10, org.openide.util.NbBundle.getMessage(OverviewControlPanel3.class, "OverviewControlPanel3.jRadioButton10.text")); // NOI18N
        jRadioButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton10ActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jLabel4, org.openide.util.NbBundle.getMessage(OverviewControlPanel3.class, "OverviewControlPanel3.jLabel4.text")); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jRadioButton10)
                    .addComponent(radioButton_Middle)
                    .addComponent(jRadioButton12))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioButton_Middle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton12)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jSeparator2)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 15, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void slider_bandSelectionStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slider_bandSelectionStateChanged
        // single selection and disable other bands
        JSlider source = (JSlider) evt.getSource();
        if (!source.getValueIsAdjusting()) {
            int fps = (int) source.getValue();
            boolean[] visible = new boolean[8];
            for (int i = 0; i < 8; i++) {
                if (i == fps) {
                    visible[7 - i] = true;
                    checkBoxRef[7 - i].setSelected(true);
                } else {
                    visible[7 - i] = false;
                    checkBoxRef[7 - i].setSelected(false);
                }
            }

            hop.setMultiDepthBandVisible(visible);
        }

        radioButton6_SS.setSelected(true);
    }//GEN-LAST:event_slider_bandSelectionStateChanged

    private void setAllBandsSelected() {
        jCheckBox1.setSelected(true);
        jCheckBox2.setSelected(true);
        jCheckBox3.setSelected(true);
        jCheckBox4.setSelected(true);
        jCheckBox5.setSelected(true);
        jCheckBox6.setSelected(true);
        jCheckBox7.setSelected(true);
        jCheckBox8.setSelected(true);
    }

    //this set of buttons for setting the dot size of seismicity
    private void jRadioButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton10ActionPerformed
        // TODO add your handling code here:
        hop.setPixelSize(6);
    }//GEN-LAST:event_jRadioButton10ActionPerformed

    private void radioButton_MiddleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButton_MiddleActionPerformed
        // TODO add your handling code here:
        hop.setPixelSize(10);
    }//GEN-LAST:event_radioButton_MiddleActionPerformed

    private void jRadioButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton12ActionPerformed
        // TODO add your handling code here:
        hop.setPixelSize(14);
    }//GEN-LAST:event_jRadioButton12ActionPerformed

    //this set of buttons for setting the hypocentre visualization options 
    private void jRadioButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton7ActionPerformed
        // TODO add your handling code here:
        hop.setHypoVisOptions(1);
    }//GEN-LAST:event_jRadioButton7ActionPerformed

    private void radioButton_StaticActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButton_StaticActionPerformed
        // TODO add your handling code here:
        hop.setHypoVisOptions(2);
    }//GEN-LAST:event_radioButton_StaticActionPerformed

    private void jRadioButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton9ActionPerformed
        // TODO add your handling code here:

        radioButton1_CB.setSelected(true);
        hop.setDepthBandOrder(4);

        hop.setHypoVisOptions(3);
    }//GEN-LAST:event_jRadioButton9ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed

        if (hop.getDepthBandVisible(0) == true) {
            hop.setSingleDepthBandVisible(0, false);
        } else {
            hop.setSingleDepthBandVisible(0, true);
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed

        if (hop.getDepthBandVisible(1) == true) {
            hop.setSingleDepthBandVisible(1, false);
        } else {
            hop.setSingleDepthBandVisible(1, true);
        }
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed

        if (hop.getDepthBandVisible(2) == true) {
            hop.setSingleDepthBandVisible(2, false);
        } else {
            hop.setSingleDepthBandVisible(2, true);
        }
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void jCheckBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox4ActionPerformed

        if (hop.getDepthBandVisible(3) == true) {
            hop.setSingleDepthBandVisible(3, false);
        } else {
            hop.setSingleDepthBandVisible(3, true);
        }
    }//GEN-LAST:event_jCheckBox4ActionPerformed

    private void jCheckBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox5ActionPerformed

        if (hop.getDepthBandVisible(4) == true) {
            hop.setSingleDepthBandVisible(4, false);
        } else {
            hop.setSingleDepthBandVisible(4, true);
        }
    }//GEN-LAST:event_jCheckBox5ActionPerformed

    private void jCheckBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox6ActionPerformed

        if (hop.getDepthBandVisible(5) == true) {
            hop.setSingleDepthBandVisible(5, false);
        } else {
            hop.setSingleDepthBandVisible(5, true);
        }
    }//GEN-LAST:event_jCheckBox6ActionPerformed

    private void jCheckBox7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox7ActionPerformed

        if (hop.getDepthBandVisible(6) == true) {
            hop.setSingleDepthBandVisible(6, false);
        } else {
            hop.setSingleDepthBandVisible(6, true);
        }
    }//GEN-LAST:event_jCheckBox7ActionPerformed

    private void jCheckBox8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox8ActionPerformed

        if (hop.getDepthBandVisible(7) == true) {
            hop.setSingleDepthBandVisible(7, false);
        } else {
            hop.setSingleDepthBandVisible(7, true);
        }
    }//GEN-LAST:event_jCheckBox8ActionPerformed

    private void radioButton6_SSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButton6_SSActionPerformed
        // TODO add your handling code here:
        //jSlider2.setValue(7-hop.getCurrentBand());

        int fps = (int) slider_bandSelection.getValue();
        boolean[] visible = new boolean[8];
        for (int i = 0; i < 8; i++) {
            if (i == fps) {
                visible[7 - i] = true;
                checkBoxRef[7 - i].setSelected(true);
            } else {
                visible[7 - i] = false;
                checkBoxRef[7 - i].setSelected(false);
            }
        }

        radioButton6_SS.setSelected(true);
        hop.setMultiDepthBandVisible(visible);
        hop.setDepthBandOrder(6);
    }//GEN-LAST:event_radioButton6_SSActionPerformed

    private void radioButton1_CBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButton1_CBActionPerformed
        /*
        * neighbour bands first
        */
        radioButton1_CB.setSelected(true);
        radioButton_Static.setSelected(true);
        setAllBandsSelected();
        hop.setDepthBandOrder(4);
    }//GEN-LAST:event_radioButton1_CBActionPerformed

    private void radioButton4_ROActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButton4_ROActionPerformed
        // random
        slider_bandSelection.setValue(7 - hop.getCurrentBand());
        radioButton4_RO.setSelected(true);
        setAllBandsSelected();
        hop.setDepthBandOrder(3);
    }//GEN-LAST:event_radioButton4_ROActionPerformed

    private void radioButton5_AnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButton5_AnActionPerformed
        // animation
        slider_bandSelection.setValue(7 - hop.getCurrentBand());
        radioButton5_An.setSelected(true);
        setAllBandsSelected();

        // set hypo anim to non
        radioButton_Static.setSelected(true);

        hop.setDepthBandOrder(5);
        hop.setHypoVisOptions(2);
    }//GEN-LAST:event_radioButton5_AnActionPerformed

    private void radioButton3_SBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButton3_SBActionPerformed
        //shallow first
        slider_bandSelection.setValue(7 - hop.getCurrentBand());
        radioButton3_SB.setSelected(true);
        setAllBandsSelected();
        hop.setDepthBandOrder(2);
    }//GEN-LAST:event_radioButton3_SBActionPerformed

    private void radioButton2_DBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButton2_DBActionPerformed
        // deep first
        slider_bandSelection.setValue(7 - hop.getCurrentBand());
        setAllBandsSelected();
        hop.setDepthBandOrder(1);
        radioButton2_DB.setSelected(true);
    }//GEN-LAST:event_radioButton2_DBActionPerformed

    public void resetOrderHypoOption() {
        radioButton1_CB.setSelected(true);
        radioButton_Static.setSelected(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton12;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JRadioButton radioButton1_CB;
    private javax.swing.JRadioButton radioButton2_DB;
    private javax.swing.JRadioButton radioButton3_SB;
    private javax.swing.JRadioButton radioButton4_RO;
    private javax.swing.JRadioButton radioButton5_An;
    private javax.swing.JRadioButton radioButton6_SS;
    private javax.swing.JRadioButton radioButton_Middle;
    private javax.swing.JRadioButton radioButton_Static;
    private javax.swing.JSlider slider_bandSelection;
    // End of variables declaration//GEN-END:variables

}
