package uk.ac.isc.stationazimuthview;

import java.awt.BorderLayout;
import javax.swing.JScrollPane;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.util.NbBundle.Messages;
import org.openide.windows.TopComponent;
import uk.ac.isc.seisdatainterface.Global;
import uk.ac.isc.seisdata.Hypocentre;
import uk.ac.isc.seisdata.HypocentresList;
import uk.ac.isc.seisdata.PhasesList;
import uk.ac.isc.seisdata.SeisDataChangeEvent;
import uk.ac.isc.seisdata.SeisDataChangeListener;
import uk.ac.isc.seisdata.SeisEvent;
import uk.ac.isc.seisdata.VBASLogger;

/**
 * Top component which displays station azimuth view.
 */
@ConvertAsProperties(
        dtd = "-//uk.ac.isc.stationazimuthview//StationAzimuthView//EN",
        autostore = false
)
@TopComponent.Description(
        preferredID = "StationAzimuthViewTopComponent",
        //iconBase="SET/PATH/TO/ICON/HERE", 
        persistenceType = TopComponent.PERSISTENCE_ALWAYS
)
@TopComponent.Registration(mode = "properties", openAtStartup = false)
@ActionID(category = "Window", id = "uk.ac.isc.stationazimuthview.StationAzimuthViewTopComponent")
@ActionReference(path = "Menu/Window" /*, position = 333 */)
@TopComponent.OpenActionRegistration(
        displayName = "#CTL_StationAzimuthViewAction",
        preferredID = "StationAzimuthViewTopComponent"
)
@Messages({
    "CTL_StationAzimuthViewAction=StationAzimuthView",
    "CTL_StationAzimuthViewTopComponent=StationAzimuthView Window",
    "HINT_StationAzimuthViewTopComponent=This is a StationAzimuthView window"
})

public final class StationAzimuthViewTopComponent extends TopComponent implements SeisDataChangeListener {

    private final JScrollPane scrollPane;

    // control panel of the view
    private final StationAzimuthControlPanel sacp;
    // the main view 
    private final StationAzimuthView saView;

    private static SeisEvent selectedSeisEvent = Global.getSelectedSeisEvent();
    private final PhasesList phasesList = Global.getPhasesList();
    private final HypocentresList hyposList = Global.getHypocentresList();

    public StationAzimuthViewTopComponent() {
        initComponents();
        setName(Bundle.CTL_StationAzimuthViewTopComponent());
        setToolTipText(Bundle.HINT_StationAzimuthViewTopComponent());
        putClientProperty(TopComponent.PROP_CLOSING_DISABLED, Boolean.TRUE);
        putClientProperty(TopComponent.PROP_SLIDING_DISABLED, Boolean.TRUE);
        putClientProperty(TopComponent.PROP_UNDOCKING_DISABLED, Boolean.TRUE);
        setName("Station Geometry");

        VBASLogger.logDebug("Loaded...");

        selectedSeisEvent.addChangeListener(this);

        saView = new StationAzimuthView(hyposList, phasesList);
        sacp = new StationAzimuthControlPanel(saView);

        scrollPane = new JScrollPane(saView);
        this.setLayout(new BorderLayout());
        this.add(scrollPane, BorderLayout.CENTER);
        this.add(sacp, BorderLayout.NORTH);
    }

    //repaint the view when data changes
    @Override
    public void SeisDataChanged(SeisDataChangeEvent event) {
        String eventName = event.getData().getClass().getName();
        VBASLogger.logDebug("Event received from: " + eventName);

        switch (eventName) {
            case "uk.ac.isc.seisdata.SeisEvent":
                //SeisEvent seisEvent = (SeisEvent) event.getData();
                VBASLogger.logDebug("SeisEvent= " + selectedSeisEvent.getEvid());
                saView.updateData();
                scrollPane.setViewportView(saView);
                break;
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {
        // TODO add custom code on component opening
        //phasesList.addChangeListener(this);
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
        //phasesList.removeChangeListener(this);
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }

}
