package uk.ac.isc.agencypiechartview;

import java.awt.BorderLayout;
import javax.swing.JScrollPane;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.util.NbBundle.Messages;
import org.openide.windows.TopComponent;
import uk.ac.isc.seisdatainterface.Global;
import uk.ac.isc.seisdata.PhasesList;
import uk.ac.isc.seisdata.SeisDataChangeEvent;
import uk.ac.isc.seisdata.SeisDataChangeListener;
import uk.ac.isc.seisdata.SeisEvent;
import uk.ac.isc.seisdata.VBASLogger;

/**
 * Top component which displays pie chart view.
 */
@ConvertAsProperties(
        dtd = "-//uk.ac.isc.agencypiechartview//AgencyPieChartView//EN",
        autostore = false
)
@TopComponent.Description(
        preferredID = "AgencyPieChartViewTopComponent",
        //iconBase="SET/PATH/TO/ICON/HERE", 
        persistenceType = TopComponent.PERSISTENCE_ALWAYS
)
@TopComponent.Registration(mode = "explorer", openAtStartup = true)
@ActionID(category = "Window", id = "uk.ac.isc.agencypiechartview.AgencyPieChartViewTopComponent")
@ActionReference(path = "Menu/Window" /*, position = 333 */)
@TopComponent.OpenActionRegistration(
        displayName = "#CTL_AgencyPieChartViewAction",
        preferredID = "AgencyPieChartViewTopComponent"
)
@Messages({
    "CTL_AgencyPieChartViewAction=Agency Summary",
    "CTL_AgencyPieChartViewTopComponent=Agency Summary",
    "HINT_AgencyPieChartViewTopComponent=Agency Summary"
})
public final class AgencyPieChartViewTopComponent extends TopComponent implements SeisDataChangeListener {

    //processed data with sorted percentages
    private final PieChartData pcData;
    private final JScrollPane scrollPane;
    //the key class of the piechart
    private final AgencyPieChartView apcView = new AgencyPieChartView();

    private static SeisEvent selectedSeisEvent = Global.getSelectedSeisEvent();
    private final PhasesList phasesList = Global.getPhasesList();

    public AgencyPieChartViewTopComponent() {
        initComponents();
        setName(Bundle.CTL_AgencyPieChartViewTopComponent());
        setToolTipText(Bundle.HINT_AgencyPieChartViewTopComponent());
        putClientProperty(TopComponent.PROP_CLOSING_DISABLED, Boolean.TRUE);
        putClientProperty(TopComponent.PROP_SLIDING_DISABLED, Boolean.FALSE);
        putClientProperty(TopComponent.PROP_UNDOCKING_DISABLED, Boolean.FALSE);
        //setName("Agency Summary");

        VBASLogger.logDebug("Loaded... #phases: " + phasesList.getPhases().size());

        selectedSeisEvent.addChangeListener(this);

        pcData = new PieChartData(phasesList.getPhases());
        apcView.setData(pcData);

        scrollPane = new JScrollPane(apcView);
        this.setLayout(new BorderLayout());
        this.add(scrollPane, BorderLayout.CENTER);
    }

    //once the phase data changes, repaint the figure
    @Override
    public void SeisDataChanged(SeisDataChangeEvent event) {

        String eventName = event.getData().getClass().getName();
        VBASLogger.logDebug(" Event received from " + eventName);

        // It only received SeiesEvent selected/changed now
        switch (eventName) {
            case ("uk.ac.isc.seisdata.SeisEvent"):
                //SeisEvent seisEvent = (SeisEvent) event.getData();
                VBASLogger.logDebug("SeisEvent= " + selectedSeisEvent.getEvid());

                pcData.UpdateData(phasesList.getPhases());
                apcView.repaint();
                scrollPane.setViewportView(apcView);
                break;
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {
        // TODO add custom code on component opening
        //phasesList.addChangeListener(this);
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
        //phasesList.removeChangeListener(this);
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }

}
